[colors]
[colors.primary]
background = "#041419"
foreground = "#fdf9fb"

[colors.normal]
black   = "#041419"
red     = "#a78181"
green   = "#8ba7ad"
yellow  = "#BCA961"
blue    = "#9ca0b9"
magenta = "#c2a3bf"
cyan    = "#a8d3e9"
white   = "#DFBBCE"

[colors.bright]
black   = "#458195"
red     = "#ceb6b6"
green   = "#c0d0d4"
yellow  = "#dace9f"
blue    = "#d1d3e0"
magenta = "#e7dae6"
cyan    = "#d9edf7"
white   = "#fdf9fb"

[colors.cursor]
text   = "#041419"
cursor = "#fdf9fb"
